### ISSUE TITLE
Missing interface's property

### ISSUE THREAD

**Issue by olishevskii** [googleapis/nodejs-storage#2464] opened 2024-05-12 19:34 UTC
Why doesn't the second element of the array have the property pageToken?
https://github.com/googleapis/nodejs-storage/blob/b4dbd73189b9fae4c23d614753670ee562bc717b/src/bucket.ts#L90
<img width="697" alt="Screenshot 2024-05-12 at 21 11 41" src="https://github.com/googleapis/nodejs-storage/assets/77493533/9b73e021-66f9-4c46-aeff-87bb6bac3986">

 This property will be present if you pass `{ autoPaginate: false }` into `Storage.getFiles`.

**Comment by bajajneha27** [comment] 2024-05-14 11:21
Hi @olishevskii 
That's probably because you don't  have enough objects for the next page. By default, we return `1000` objects. If you do want to limit the number of objects returned, use `maxResults` option and then you should be able to see `nextPage` as well.

```
let [files, nextPage] = await bucket.getFiles({autoPaginate: false, maxResults: 10});
```

Hope this helps. I'm closing the issue now. Please feel free to re-open it if there's any other issue.

**Comment by olishevskii** [comment] 2024-05-14 11:32
Hi @bajajneha27. Thank you for your answer.

No, it's not working because there's a problem with the interface
<img width="825" alt="Screenshot 2024-05-14 at 15 30 10" src="https://github.com/googleapis/nodejs-storage/assets/77493533/f3335913-0634-4971-b753-15b2adbdefcc">
<img width="424" alt="Screenshot 2024-05-14 at 15 30 30" src="https://github.com/googleapis/nodejs-storage/assets/77493533/e05f7295-12ce-43bf-bc8b-44950b868cdf">

**Comment by bajajneha27** [comment] 2024-05-14 12:26
I see.
Well, I'm getting the `nextPage` populated. Can you help me with a code snippet so that I can try to reproduce this?

**Comment by ddelgrosso1** [comment] 2024-05-14 13:56
@bajajneha27 no need to reproduce, the currently defined type is just a generic object. The issue is that it should be more clearly typed which is what @olishevskii is working on in the linked PR.

**Closed** 2024-05-14 18:38 UTC
Labels: type: question, api: storage
