### ISSUE TITLE
file upload not working. Issue with readable-stream.

### ISSUE THREAD

**Issue by JunedBrilworks** [googleapis/nodejs-storage#2008] opened 2022-07-27 13:53 UTC
I'm trying to upload the file but it's not working. Some issues with dependency related to readable-stream.
<img width="1036" alt="Screenshot 2022-07-27 at 19 13 51" src="https://user-images.githubusercontent.com/93306798/181263255-374b269c-b5f6-48f8-b222-d7380b197655.png">

here is the code snippet

`bucket.upload(filepath,options,function (err, file) { // uploaded})`

My package.json
[package.txt](https://github.com/googleapis/nodejs-storage/files/9199509/package.txt)

My yarn-lock file
[yarn.txt](https://github.com/googleapis/nodejs-storage/files/9199516/yarn.txt)

**Comment by ddelgrosso1** [comment] 2022-07-27 15:39
Hi @JunedBrilworks thank you for reporting this issue. Could you provide us with a few more details, what are the options you are currently passing to `bucket.upload`? Was this working for you in a previous version of the storage library?

**Comment by JunedBrilworks** [comment] 2022-07-28 03:40
@ddelgrosso1 I have only worked with the current version so not sure if it's an issue with old version also. I will try with previous version also

Options parameters are as below
```
{
      resumable: false,
      gzip: true,
}
```

**Comment by ddelgrosso1** [comment] 2022-07-28 13:34
Thanks @JunedBrilworks I will take a look and try to reproduce. I will update accordingly.

**Comment by ddelgrosso1** [comment] 2022-07-28 14:25
One other question, what version of node are you running this with? I created a quick test with the following code (node 16.13.2):

```javascript
  const s = new Storage({projectId: 'redacted-project-id'});
  const b = s.bucket('redacted-bucket-name');
  b.upload("sample.jpg", {
    gzip: true,
    resumable: false
  }, (err, res) => {
    console.log("In Upload Callback");
    console.log(err);
    console.log(res);
  });
```

I did not see the error you indicated above.

**Comment by ddelgrosso1** [comment] 2022-08-05 14:21
I have been unsuccessful in reproducing this issue. Since additional information has not been provided I am going to close this. If additional information becomes available please feel free to reopen.

**Closed by ddelgrosso1** 2022-08-05 14:21 UTC
Labels: type: bug, priority: p2, api: storage
