### ISSUE TITLE
How to upload a file in chunks?

### ISSUE THREAD

**Issue by gajus** [googleapis/nodejs-storage#1191] opened 2020-05-13 22:29 UTC
I am loosing my mind here, since I think I've tried absolutely everything and I still cannot figure out what is the proper way to do it.

Suppose I have a 0.9MB file.

```bash
$ ll
-rw-r--r--@  1 gajus  staff   921K 13 May 14:38 test.png

```

I then split that file into 2 chunks:

```bash
$ split -b 1000000 test.png
$ ll
-rw-r--r--@  1 gajus  staff   921K 13 May 14:38 test.png
-rw-r--r--   1 gajus  staff   488K 13 May 14:56 xaa
-rw-r--r--   1 gajus  staff   433K 13 May 14:56 xab

```

Assuming I only have access to the resulting chunks (and they might be on different servers, i.e. must be two distinct operations), what is the correct way to upload test.png?

Here is what I tried:

```js
(async () => {
  const googleStorageBucket = googleStorage.bucket('contrawork');
  const file = googleStorageBucket.file('images/test.png');
  const uri = (await file.createResumableUpload())[0];

  await googleStorageBucket.upload('./xaa', {
    gzip: false,
    offset: 0,
    predefinedAcl: 'publicRead',
    resumable: true,
    uri,
    validation: false,
  });

  await googleStorageBucket.upload('./xab', {
    gzip: false,
    offset: 500000,
    predefinedAcl: 'publicRead',
    resumable: true,
    uri,
    validation: false,
  });
})();

```

However, this uploads only first image. The second file is never appended.

[images_test.png.zip](https://github.com/googleapis/google-cloud-node/files/4624954/images_test.png.zip)

There is no error or anything. It seems that PUT requests are simply ignored.

The first request/respone:

```
 PUT https://storage.googleapis.com/upload/storage/v1/b/contrawork/o?name=images%2Ftest.png&uploadType=resumable&upload_id=[..]

Content-Range:      bytes 0-*/*
Authorization:      Bearer [..]
User-Agent:         google-api-nodejs-client/5.10.1
x-goog-api-client:  gl-node/14.1.0 auth/5.10.1
Accept:             application/json
Accept-Encoding:    gzip,deflate
Connection:         close
Host:               storage.googleapis.com
Transfer-Encoding:  chunked

```

```json
{
  "kind": "storage#object",
  "id": "contrawork/images/test.png/1589408553615624",
  "selfLink": "https://www.googleapis.com/storage/v1/b/contrawork/o/images%2Ftest.png",
  "mediaLink": "https://storage.googleapis.com/download/storage/v1/b/contrawork/o/images%2Ftest.png?generation=1589408553615624&alt=media",
  "name": "images/test.png",
  "bucket": "contrawork",
  "generation": "1589408553615624",
  "metageneration": "1",
  "storageClass": "NEARLINE",
  "size": "500000",
  "md5Hash": "qCGVMqig4yOiO2yoeRnvNg==",
  "crc32c": "KQhJug==",
  "etag": "CIiC96HwsekCEAE=",
  "timeCreated": "2020-05-13T22:22:33.615Z",
  "updated": "2020-05-13T22:22:33.615Z",
  "timeStorageClassUpdated": "2020-05-13T22:22:33.615Z"
}

```

The second:

```
https://storage.googleapis.com/upload/storage/v1/b/contrawork/o?name=images%2Ftest.png&uploadType=resumable&upload_id=[..]

Content-Range:      bytes 500000-*/*
Authorization:      [..]
User-Agent:         google-api-nodejs-client/5.10.1
x-goog-api-client:  gl-node/14.1.0 auth/5.10.1
Accept:             application/json
Accept-Encoding:    gzip,deflate
Connection:         close
Host:               storage.googleapis.com
Transfer-Encoding:  chunked

```

```json
{
  "kind": "storage#object",
  "id": "contrawork/images/test.png/1589408553615624",
  "selfLink": "https://www.googleapis.com/storage/v1/b/contrawork/o/images%2Ftest.png",
  "mediaLink": "https://storage.googleapis.com/download/storage/v1/b/contrawork/o/images%2Ftest.png?generation=1589408553615624&alt=media",
  "name": "images/test.png",
  "bucket": "contrawork",
  "generation": "1589408553615624",
  "metageneration": "1",
  "storageClass": "NEARLINE",
  "size": "500000",
  "md5Hash": "qCGVMqig4yOiO2yoeRnvNg==",
  "crc32c": "KQhJug==",
  "etag": "CIiC96HwsekCEAE=",
  "timeCreated": "2020-05-13T22:22:33.615Z",
  "updated": "2020-05-13T22:22:33.615Z",
  "timeStorageClassUpdated": "2020-05-13T22:22:33.615Z"
}


```

**Comment by laljikanjareeya** [comment] 2020-05-14 12:04
Duplicate of #1192

**Closed by laljikanjareeya** 2020-05-14 12:04 UTC
Labels: api: storage
