### ISSUE TITLE
STORAGE_EMULATOR_HOST getting TypeError: Only HTTP(S) protocols are supported

### ISSUE THREAD

**Issue by Ridermansb** [googleapis/nodejs-storage#2158] opened 2023-03-05 11:58 UTC
I have my firebase local emulator running with storage on port 9199

![image](https://user-images.githubusercontent.com/725337/222958767-ab92e5bd-b88c-4a79-bea7-404f8060d981.png)

I set the `STORAGE_EMULATOR_HOST=localhost:9199` 

**I initialize my cloud storage as this..**

```javascript
import { Storage } from "@google-cloud/storage";
const storage = new Storage();

log('Storage running with config "%o"', {
  projectId: storage.projectId, // '{{projectId}}'
  apiEndpoint: storage.apiEndpoint, // 'https://localhost:9199'
  baseUrl: storage.baseUrl // 'localhost:9199'
});
```

When I tried to upload the file to my local storage emulator using this code..

```javascript
  const bucket = storage.bucket("gs://{{MY_PROJECT_ID}}.appspot.com");
  const file = bucket.file(`user-url-assets/${userUrl.id}}/${fileName}`);
  return file.save(buffer, {
    public: true,
    metadata: {
      cacheControl: "public, max-age=31536000",
      metadata: {
        ...userUrl
      }
    }
  });
```

## I'm getting this error:

>  /Users/ridermansb/Projects/mine/pageHistory/web/node_modules/node-fetch/lib/index.js:1331
                throw new TypeError('Only HTTP(S) protocols are supported');
                      ^
> TypeError: Only HTTP(S) protocols are supported
    at getNodeRequestOptions (/Users/ridermansb/Projects/mine/pageHistory/web/node_modules/node-fetch/lib/index.js:1331:9)
    at /Users/ridermansb/Projects/mine/pageHistory/web/node_modules/node-fetch/lib/index.js:1454:19
    at new Promise (<anonymous>)
    at fetch (/Users/ridermansb/Projects/mine/pageHistory/web/node_modules/node-fetch/lib/index.js:1451:9)
    at teenyRequest (/Users/ridermansb/Projects/mine/pageHistory/web/node_modules/teeny-request/build/src/index.js:203:30)
    at Object.request (/Users/ridermansb/Projects/mine/pageHistory/web/node_modules/teeny-request/build/src/index.js:243:9)
    at Timeout.makeRequest [as _onTimeout] (/Users/ridermansb/Projects/mine/pageHistory/web/node_modules/retry-request/index.js:171:28)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

**Some environment variables are set**

```
  FIRESTORE_EMULATOR_HOST: 'localhost:8080',
  FIREBASE_AUTH_EMULATOR_HOST: 'localhost:9099',
  FIREBASE_PUBSUB_EMULATOR_HOST: 'localhost:8085',
  FIREBASE_STORAGE_EMULATOR_HOST: 'localhost:9199',
  STORAGE_EMULATOR_HOST: 'localhost:9199',
  GCLOUD_PROJECT: '{{PROJECT_ID}}'
```

**Comment by ddelgrosso1** [comment] 2023-03-06 15:32
Hi @Ridermansb the recommendation currently is to use `apiEndpoint`. `STORAGE_EMULATOR_HOST` is noted as [experimental](https://github.com/googleapis/nodejs-storage/blob/41008055a7f5f6e1a2734b2d8b2695d4faf18102/src/storage.ts#L689). There are some other issues being worked on around compatibility with the Firebase Emulator https://github.com/googleapis/nodejs-storage/issues/2092.

**Comment by Ridermansb** [comment] 2023-03-08 20:26
Hey @ddelgrosso1 .. I tried as well.. get the same results :(

**Comment by ddelgrosso1** [comment] 2023-05-04 20:57
Going to close this as I am unable to reproduce locally. If more information on recreating this becomes available please feel free to reopen with the additional info.

**Closed by ddelgrosso1** 2023-05-04 20:57 UTC
Labels: type: question, api: storage, priority: p3

**Comment by jelling** [comment] 2023-11-07 10:41
At least in my case, root cause appears to be that the storage library is passing the IP address into the protocol property when it calls `node-fetch`:

![Screen Shot 2023-11-07 at 11 23 48 AM](https://github.com/googleapis/nodejs-storage/assets/1887486/abfbe694-4850-4959-9887-85f13b086b1d)

Like OP, this happens even when using the `apiEndpoint` property:

```
  const s = new Storage({
    projectId: "reboot-tv-test",
    // neither http or https work
    // apiEndpoint: "http://127.0.0.1:9199",
    apiEndpoint: "https://127.0.0.1:9199",
  });
  const b = s.bucket("gs://reboot-tv-test.appspot.com");
  const file = b.file(storagePath);
  const tmpFilePath = `${os.tmpdir()}/${storagePath}`;
  await file.download({ destination: tmpFilePath, validation: false });
```

**Comment by ivansalacceo** [comment] 2024-11-15 08:45
I solved this issue by changing the environment variable of STORAGE_EMULATOR_HOST to use http

```
FIRESTORE_EMULATOR_HOST: 'localhost:8080',
FIREBASE_STORAGE_EMULATOR_HOST: 'localhost:9199',
STORAGE_EMULATOR_HOST: 'http://localhost:9199'
```

**Comment by Ridermansb** [comment] 2025-01-07 11:53
> apiEndpoint: "https://127.0.0.1:9199",

To reproduce it's simple.

1. Create an API that uses HTTPS.
2. On that API, try uploading something to storage with the environment variable set to.`STORAGE_EMULATOR_HOST: 'localhost:9199'`

If you run the API under HTTP, you will not be able to reproduce it.
