### ISSUE TITLE
Error 502 (Server Error)!!1

### ISSUE THREAD

**Issue by gajus** [googleapis/nodejs-storage#1233] opened 2020-07-06 13:52 UTC
#### Environment details

  - OS: Debian
  - Node.js version: 14
  - `@google-cloud/storage` version: 5.1.1

#### Steps to reproduce

```js
await googleStorageBucket.upload(transcodedFilePath, {
  destination: 'images/' + uid,
  gzip: false,
  metadata: {
    contentType: 'image/webp',
    storageClass: 'STANDARD',
  },
  onUploadProgress: createFileUploadProgressEventHandler(
    'transcoded image',
    uid,
    transcodedFileStat.size,
  ),
  predefinedAcl: 'bucketOwnerFullControl',
  resumable: false,
  validation: 'crc32c',
});
```

Occasionally fails with:

```yaml
statusCode:     502
statusMessage:  Bad Gateway
headers:
  User-Agent:        gcloud-node-storage/5.1.1
  x-goog-api-client: gl-node/14.5.0 gccl/5.1.1
  Authorization:     Bearer [..]
  Content-Type:      multipart/related; boundary=925dbc29-dd20-4554-b36b-89ebb41850c2
href:    https://storage.googleapis.com/upload/storage/v1/b/contrawork/o?uploadType=multipart&name=images%2F0c902ad8-403f-6000-9758-fe7194509706&predefinedAcl=bucketOwnerFullControl
body:
  """
    <!DOCTYPE html>
    <html lang=en>
      <meta charset=utf-8>
      <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
      <title>Error 502 (Server Error)!!1</title>
      <style>
        *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
      </style>
      <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
      <p><b>502.</b> <ins>That’s an error.</ins>
      <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>

  """

```

There appears to be no built in logic to retry these errors.

I worked around this issue by adding a generic retry wrapper above the `googleStorageBucket.upload` function. However, (1) I am still getting many of these errors logged (2) this [retry logic] looks like something that should be handled by `@google-cloud/storage`

**Comment by gajus** [comment] 2020-07-06 14:28
Looking at the `@google/common`, it would appear that this request should be already retried by default.

https://github.com/googleapis/nodejs-common/blob/master/src/util.ts#L515-L517

**Comment by stephenplusplus** [comment] 2020-07-28 19:05
@gajus sorry for this long of a wait for a reply. I haven't been able to reproduce, although, this appears to be one that's hard to produce in nature. Any extra advice on replicating your scenario is welcome. Also, I was wondering how you were able to confirm the request wasn't retried? I believe the error would still come back, after a certain number of retry attempts is reached. Thanks!

**Comment by gajus** [comment] 2020-07-28 21:12
> Also, I was wondering how you were able to confirm the request wasn't retried? I believe the error would still come back, after a certain number of retry attempts is reached. Thanks!

Looking at the task execution logs, there is no great difference between succeeding file upload tasks and those that fail with this error. Which means that upload is either not being retried or that not enough retries/ not great enough interval is used.

> I worked around this issue by adding a generic retry wrapper above the googleStorageBucket.upload function. However, (1) I am still getting many of these errors logged (2) this [retry logic] looks like something that should be handled by @google-cloud/storage

Besides, adding retry wrapper did "solve" the problem, i.e. all tasks are completing with image successfully being uploaded. We are using at most 3 retries with 2, 4, 8 second delay increments.

> I haven't been able to reproduce, although,

For what it is worth, I am seeing the same issue in two completely separate projects (at work and on my hobby project), i.e. does not seem to be account specific.

**Comment by gajus** [comment] 2020-07-28 21:14
Somewhat surprisingly, I am not seeing many more issues come up when searching "Error 502 (Server Error)!!1" and "@google-cloud/storage". I was expecting a lot more people to comment on this issue.

The only thing that is similar between the two different projects that I mention, is that they are both hosted on GKE and they both use @google-cloud/storage.

**Comment by stephenplusplus** [comment] 2020-09-16 17:01
You're right! The core issue here is that multipart uploads aren't retried-- earlier in the thread, I assumed they were, but forget we intentionally do not retry it. That's because we send the request as a stream, and once data leaves the source stream, we can't get it back in the event we get an error and want to send the upload request again. In the case of "file.save(blob)", it uses "file.createWriteStream()" beneath. Since we already were given the blob by the user, and have it in memory, we can definitely send it again. It's just a matter of figuring out how to plug that into our library. This PR is looking into that: https://github.com/googleapis/nodejs-storage/pull/1282

**Comment by ahmedbrandver** [comment] 2020-11-30 05:58
Getting  the same issue with cloud-storage using the latest version of gcloud for node i.e. 5.5.0. Error I am facing

```
Uncaught exception in ApiError: Cannot parse response as JSON: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 408 (Request Timeout)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>408.</b> <ins>That’s an error.</ins>
  <p>Your client has taken too long to issue its request.  <ins>That’s all we know.</ins>

    at Util.parseHttpRespBody (/var/app/current/node_modules/@google-cloud/common/build/src/util.js:188:42)
    at Util.handleResp (/var/app/current/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at /var/app/current/node_modules/@google-cloud/common/build/src/util.js:432:22
    at onResponse (/var/app/current/node_modules/retry-request/index.js:206:7)
    at /var/app/current/node_modules/teeny-request/build/src/index.js:170:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  **message**: 'Cannot parse response as JSON: <!DOCTYPE html>\n' +
    '<html lang=en>\n' +
    '  <meta charset=utf-8>\n' +
    '  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n' +
    '  <title>Error 408 (Request Timeout)!!1</title>\n' +
    '  <style>\n' +
    '    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n' +
    '  </style>\n' +
    '  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n' +
    '  <p><b>408.</b> <ins>That’s an error.</ins>\n' +
    '  <p>Your client has taken too long to issue its request.  <ins>That’s all we know.</ins>\n',
  **response**: PassThrough {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: false,
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      error: [Array],
      data: [Function],
      end: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: false,
    allowHalfOpen: true,
    _transformState: {
      afterTransform: [Function: bound afterTransform],
      needTransform: false,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: 'buffer'
    },
    statusCode: 408,
    statusMessage: 'Request Timeout',
    request: {
      agent: [Agent],
      headers: [Object],
      href: 'https://storage.googleapis.com/upload/storage/v1/b/bigquery-sync/o?uploadType=multipart&name=bigquery-upload-joblogs-1585740331077-1.json'
    },
    **body**: '<!DOCTYPE html>\n' +
      '<html lang=en>\n' +
      '  <meta charset=utf-8>\n' +
      '  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n' +
      '  <title>Error 408 (Request Timeout)!!1</title>\n' +
      '  <style>\n' +
      '    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n' +
      '  </style>\n' +
      '  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n' +
      '  <p><b>408.</b> <ins>That’s an error.</ins>\n' +
      '  <p>Your client has taken too long to issue its request.  <ins>That’s all we know.</ins>\n',
    headers: {
      'alt-svc': 'quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000',
      connection: 'close',
      'content-length': '1557',
      'content-type': 'text/html; charset=UTF-8',
      date: 'Wed, 01 Apr 2020 11:37:20... 
```

Follow up with:

```
FetchError: request to https://www.googleapis.com/oauth2/v4/token failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/usr/app/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  message: 'request to https://www.googleapis.com/oauth2/v4/token failed, reason: Client network socket disconnected before secure TLS connection was established',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  config: {
    method: 'POST',
    url: 'https://www.googleapis.com/oauth2/v4/token',
    data: {
      grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer',
      assertion: 'eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ0ZWxlcG9ydC1zZXJ2aWNlQHZlcnNpZnkuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJzY29wZSI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL2F1dGgvaWFtIGh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL2F1dGgvY2xvdWQtcGxhdGZvcm0gaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vYXV0aC9kZXZzdG9yYWdlLmZ1bGxfY29udHJvbCIsImF1ZCI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92NC90b2tlbiIsImV4cCI6MTYwNjcxNzk4OCwiaWF0IjoxNjA2NzE0Mzg4fQ.P6hQVyUScXC65qtrlwrvL2ZhgO6LnKSp4513rYFJk_OOcxoL3FS7rScTgeXSJCGEdo6LvcC4hKrHHY7MVOpTkgNn-2XRhy2rSiVVUd7xRaA7h8HKJOpQ-N3CbsfMXIBXCB-Jq-Xr9HhSF8pYWx-LbSpz_Jv_etptwqHMWDsiZG0dD1uUFeozg5L47AiTyu9r6nW94gucfcYf892piN107Baitj_wDykUHoPCdI5R7-BNo9T10-s9as3QcRUppT64ZzWMgyrE15OLyUJJJQz5gsOWY79s0TL76y0fbHk2oKul5gqeMZdjMLHk-kia2CvdvchnrMPMj4-Eqev3oMDzgA'
    },
    headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
    responseType: 'json',
    paramsSerializer: [Function: paramsSerializer],
    body: '{"grant_type":"urn:ietf:params:oauth:grant-type:jwt-bearer","assertion":"eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ0ZWxlcG9ydC1zZXJ2aWNlQHZlcnNpZnkuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJzY29wZSI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL2F1dGgvaWFtIGh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL2F1dGgvY2xvdWQtcGxhdGZvcm0gaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vYXV0aC9kZXZzdG9yYWdlLmZ1bGxfY29udHJvbCIsImF1ZCI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92NC90b2tlbiIsImV4cCI6MTYwNjcxNzk4OCwiaWF0IjoxNjA2NzE0Mzg4fQ.P6hQVyUScXC65qtrlwrvL2ZhgO6LnKSp4513rYFJk_OOcxoL3FS7rScTgeXSJCGEdo6LvcC4hKrHHY7MVOpTkgNn-2XRhy2rSiVVUd7xRaA7h8HKJOpQ-N3CbsfMXIBXCB-Jq-Xr9HhSF8pYWx-LbSpz_Jv_etptwqHMWDsiZG0dD1uUFeozg5L47AiTyu9r6nW94gucfcYf892piN107Baitj_wDykUHoPCdI5R7-BNo9T10-s9as3QcRUppT64ZzWMgyrE15OLyUJJJQz5gsOWY79s0TL76y0fbHk2oKul5gqeMZdjMLHk-kia2CvdvchnrMPMj4-Eqev3oMDzgA"}',
    validateStatus: [Function: validateStatus]
  }
}
```

2) Did someone already solve this?
  - https://github.com/googleapis/nodejs-storage/issues/833 but closed.

#### Environment details

  - OS: Docker Ubuntu
  - Node.js version: 12
  - `@google-cloud/storage` version: 5.5.0

#### Steps to reproduce

  1. I am using [Bulls Queue](https://optimalbits.github.io/bull/) and [Chokidar] https://www.npmjs.com/package/chokidar to look up the file/photos which are coming to the specific directory and moving it to queue to process further.
  2. I am using 3 processors of docker to upload all the images to gcloud along with default and my own retries which also up to 3 retries. First I always get `Your client has taken too long to issue its request` then `ECONRESET` errors

**Comment by dan-dekel** [comment] 2021-01-22 02:02
Having a similar issue when uploading to the alpha track. Not happening for production track

**Comment by shaffeeullah** [comment] 2021-01-25 18:09
This has been resolved by https://github.com/googleapis/nodejs-storage/releases/tag/v5.7.3

**Closed by shaffeeullah** 2021-01-25 18:09 UTC
Labels: :rotating_light:, api: storage, priority: p2, type: bug

**Comment by surjikal** [comment] 2021-08-06 16:06
Seeing this a bunch since upgrading from 4 to `5.10.0`
- Lots of `ECONNRESET` for `file(x).download()`.
- 502 bad gateway using `file(x).createWriteStream({resumable:false})` (I don't remember why I have resumable = false, I am 99% sure it's to deal w/ similar issues during writes).

I upgraded to 5 because I thought it would help w/ these types of issues, but it seems flakier tbh.

**Comment by shaffeeullah** [comment] 2021-08-06 17:00
Hi @surjikal , 
Can you please open a new issue with this information and also some more details (such as size of file you're uploading, file type, frequency of errors, and a small repro snippet)?
