### ISSUE TITLE
Clarify docs for md5 validation in createWriteStream

### ISSUE THREAD

**Issue by KyleAMathews** [googleapis/nodejs-storage#1829] opened 2022-03-29 00:13 UTC
It wasn't specified in the docs to set the md5 value on `metadata.md5Hash` (I had to find it in the code https://github.com/googleapis/nodejs-storage/blob/3fd84881fc48db0d9a0fed881ddfdfbab129c396/src/file.ts#L1993-L1995)

**Comment by ddelgrosso1** [comment] 2022-03-29 13:59
Thank you for raising this issue @KyleAMathews. I will add the appropriate options to the documentation for `createWriteStream`.

**Comment by KyleAMathews** [comment] 2022-03-29 17:03
Actually... this doesn't seem to be working still — we wrote a short script to test validation and when we pass in a fake md5 it still passes validation. Are we doing something wrong here? https://gist.github.com/julienp/ea8ff4557a52c403b05e7e6df18ff193

**Comment by ddelgrosso1** [comment] 2022-03-29 18:13
By providing a `md5Hash` as part of the `metadata` object it causes the server to validate the object and if it does not match the supplied hash, the object will not be created ([documentation here](https://cloud.google.com/storage/docs/hashes-etags#json-api)). Additionally, if the object is created successfully the server should return back the hash and the client will also validate the data written with the returned hash. A provided hash will not be used to validate client side. 

When you provided the fake hash was data actually written on the server?

**Comment by KyleAMathews** [comment] 2022-03-29 18:27
>When you provided the fake hash was data actually written on the server?

Yes, the file is uploaded and object created despite supplying a fake `md5Hash`

**Comment by ddelgrosso1** [comment] 2022-03-29 18:40
Let me take a closer look and try and recreate the behavior to get a better idea of what might be going on. I'll update this issue with my findings.

**Comment by ddelgrosso1** [comment] 2022-03-30 13:44
I have confirmed the behavior you are seeing and I am still investigating the root cause. It appears that this only happens when using a multipart upload (`resumable = false`). In my testing when I used a resumable upload I get an error returned from the server about the hash not being base64 encoded which would align with the information in the docs.

**Comment by KyleAMathews** [comment] 2022-03-30 15:22
I can confirm enabling `resumable` gets the expected error:

> Failed to upload file: The uploaded data did not match the data from the server. As a precaution, the file has been deleted. To be sure the content is the same, you should try uploading the file again.

**Comment by frankyn** [comment] 2022-03-30 16:53
Hi @KyleAMathews,

jumping in, I tried validating using md5 in object metadata during upload:
```nodejs
const {Storage} = require('@google-cloud/storage');
const storage = new Storage();

async function testMd5Hash() {
  const bucketName = 'my-bucket';
  const bucket = await storage.bucket(bucketName);
  file = bucket.upload("my-local-file", {
    resumable: false,
    metadata: {
      md5Hash: "blah"
    }
  });
}

testMd5Hash()
```

The only gotcha is that `md5Hash` is case sensitive so if it's not cased using camelCase it will be ignored by the API. Could you confirm if you're using `md5Hash` or `md5hash`?

**Comment by KyleAMathews** [comment] 2022-03-30 16:57
we're using `createWriteStream` as well which is different

**Comment by shaffeeullah** [comment] 2022-03-30 17:55
Hi @KyleAMathews , 

The issue here is that you're passing a buffer to the md5 field. If you try removing the buffer and instead pass a string or something like 
```
md5Hash: crypto.createHash("md5").update(data).digest(`base64`),
```
it should work. 

We're looking into why the underlying http libraries behave differently for handling the buffer, but this should unblock you for now.

**Comment by KyleAMathews** [comment] 2022-03-30 18:15
Aha! That does it — the problem was we converted the md5 to `hex` not `base64`. Thanks!

A simple code snippet for md5 would be great for the docs!

**Comment by ddelgrosso1** [comment] 2022-03-31 13:31
@KyleAMathews has this solved the issue you were having?

**Comment by ddelgrosso1** [comment] 2022-04-01 17:28
@KyleAMathews I am going to close this issue as it appears the initial problem you had been seeing has been resolved. If you feel otherwise, please feel free to reopen.

**Closed by ddelgrosso1** 2022-04-01 17:28 UTC
Labels: priority: p2, type: docs, api: storage

**Comment by KyleAMathews** [comment] 2022-04-01 17:46
Yup, I'm good now 👍
