### ISSUE TITLE
getSignedUrl is blocking the event loop

### ISSUE THREAD

**Issue by oleurud** [googleapis/nodejs-storage#1771] opened 2022-01-28 15:39 UTC
We have an Express.js API which is using signed URLs for managing media files (images, video and files). Some endpoints can return from 0 to many signed URLs and we are having huge problems with the performance of `storage.bucket(...).file(...).getSignedUrl(...)` because it is delaying the Node.js event loop (or at least this is what I think right now). The more signed URLs, the worst performance. With a very low usage, the app performance is degrading so much that it is unusable.

Using [clinic.js](https://clinicjs.org/) for profiling, we get the following event loop delay times: 
 
<img width="1457" alt="Screen Shot 2022-01-28 at 4 13 31 PM" src="https://user-images.githubusercontent.com/421145/151571839-2e34d4e0-a516-4fdd-abcf-de797c062a99.png">

and this just commenting `getSignedUrl` line:

<img width="1457" alt="Screen Shot 2022-01-28 at 4 12 51 PM" src="https://user-images.githubusercontent.com/421145/151571736-b20e4494-1c69-4086-b71a-78f66ed46cdc.png">

The tool is making:
- 50 req/s calling to an endpoint 
- the endpoint is calling in parallel (`await Promise.all([ ... ])`) 10 times to `getSignedUrl` method

#### Environment details

  - OS: Linux
  - Node.js version: 16.6.2
  - npm version: 7.20.3
  - `@google-cloud/storage` version: 5.16.0

Any clue is welcome! Thanks!

**Comment by ddelgrosso1** [comment] 2022-01-28 21:27
Hi @oleurud thank you for raising this issue. I just want to make sure I am understanding something correctly, you have an endpoint that gets called 50 req/s and each time the endpoint can potentially call `getSignedUrl` 10x, so potentially 500 calls per second? You also mention that with very low usage things become unusable, could you quantify what low usage means in this context?

**Comment by oleurud** [comment] 2022-01-31 09:58
Hi @ddelgrosso1 When I was saying 

> With a very low usage, the app performance is degrading so much that it is unusable.

I was talking about a real users usage. In our case, we started realizing about the error with just 6 users in the app and the problem appeared after a few days of use. I don't really know the real usage of the `getSignedUrl` method during that period (we are improving our metrics now after this problem), but let's say, we could make like 250 request per day.

As it was not obvious to discover the error in local environment, but it was clearly happening in our staging environment, so I used a Node.js profiling app (https://clinicjs.org/) along with a benchmarking tool ([autocannon](https://github.com/mcollina/autocannon)) in the hope of being able to reproduce and diagnose the error, as it finally was

**Comment by ddelgrosso1** [comment] 2022-01-31 14:48
Thank you for the details @oleurud. I will try and reproduce this using the steps/tools you outlined. I will let you know what I find.

**Comment by oleurud** [comment] 2022-01-31 16:47
Great Denis. We are wondering what to do in the meanwhile, any clue is welcome :) 

It would be great having [prefixes for signed URLs](https://cloud.google.com/cdn/docs/using-signed-urls#url-prefix) implemented in the library so users can avoid making a request for each element in the store. With that, the problem, if it exits, could be mitigated. We could do it a try.

Or maybe making a custom version of signed URLs (something specific for our use case, not sure if it makes sense). 

And of course, other option is just wait until your answer :)

**Comment by ddelgrosso1** [comment] 2022-01-31 17:50
@oleurud I have been able to confirm what you are seeing by creating a test application that signs 10 URLs (files) per request. I am diving a bit deeper into the code to see what, if anything can be done to possibly reduce some of the associated overhead. This may take me a little while. 

In the meantime can you help me understand your use case bit more. If I understand correctly in the real world scenario 6 users are making requests to an endpoint which signs `n` number of files/URLs. In general terms what is the purpose of this workflow and why the need to sign `n` number of URLs? Do the files being accessed change every time a user makes a new request?

**Comment by oleurud** [comment] 2022-01-31 18:48
> I have been able to confirm what you are seeing

🤘 

First of all, we are in early stage working in a B2B app where content can not bu public. All images, videos and pdfs are managed using signed URLs. Probably the most expensive in terms of `getSignedUrl` calls is a chat where our users can upload files. Every user can be in many chats. When a user is entering in a chat, we are calling for all files at the same time from the backend. We are signing the URLs every time a user calls the backend and files never change.

In another part of the application, we expect there will be fewer files, many more user reads and again loading all of them. Same as before, we are signing the URLs every time a user calls the backend and files never change (in this case they can be deleted and created again).

As you can see, we were thinking about the prefix feature because working in "groups" or in batch, is the ideal way of working for us.

**Comment by ddelgrosso1** [comment] 2022-01-31 20:34
While I investigate further one thing that comes to mind would be to get a signed url at the bucket level which would allow for a listing of the files it contains. When a user attempts to access the file, generate a url for the file at that time. Of course this assumes that you aren't supporting some sort of preview functionality and that all files that were uploaded are stored in a bucket per chat.

**Comment by oleurud** [comment] 2022-02-02 11:01
Thanks Denis but ideally we can not use it signing it by bucket even when the bucket content is not listed because we don't have a bucket per client. What about using prefixes for signed URLs? is it supported by the library? because I was doing some fast tests and I are not making it work, probably I am missing something

**Comment by ddelgrosso1** [comment] 2022-02-02 14:58
Currently prefixes are not supported by the storage library. The documentation you had linked above is actually for Cloud CDN.

**Comment by shahmirn** [comment] 2022-02-02 18:22
Hello!

We were facing a similar issue, where we were seeing performance degradation in cloud run, but the performance as acceptable on our local machines.

We ended up changing our code so that we specified the credentials ourselves, instead of relying on google getting them from their metadata server in the cloud.

So, our code looks something like:

```typescript
let parsedPrivateKey;
try {
  parsedPrivateKey = JSON.parse(googleStorageCredentials.privateKey);
} catch (err) {
  parsedPrivateKey = googleStorageCredentials.privateKey;
}

const storageClient = new Storage({
  projectId: googleCredentials.projectId,
  credentials: {
    client_email: googleStorageCredentials.clientEmail,
    private_key: parsedPrivateKey,
  },
});
```

**Comment by ddelgrosso1** [comment] 2022-02-02 19:53
Hi @shahmirn I just want to confirm that you are also utilizing the `getSignedUrl` function? If so, is there a point at which you see the degradation, i.e. some period of time or does it happen immediately in Cloud Run?

**Comment by shahmirn** [comment] 2022-02-03 00:19
Hi!

Yes, to clarify, this was with usage of getSignedUrl.

For us, it was the number of documents we were signing in "parallel" using Promise.all

For something like 3 or 4, all the promises resolved in a total of less than a second

For something like 600 calls to getSignedUrl, the promise.all was finishing in 13+ seconds.

Changing to manually setting the private key resulted in the promises to finish in ~3 to 4 seconds, which is acceptable for our use-case.

**Comment by ddelgrosso1** [comment] 2022-02-03 15:39
Thank you for the additional details @shahmirn. @oleurud could you share how you are handling credentials / keys in your application?

**Comment by ibrahimmenem** [comment] 2022-02-03 15:59
Hi Denis and Shahmir,

I work with @oleurud and the way we handle credentials in cloud run is by assigning the proper service account to cloud run service (I guess underneath it is uses the internal metadata server) **but the profiling and tests** were done in local by providing service account key via GOOGLE_APPLICATION_CREDENTIALS environment variable. 

Our theory is that while we could gain some performance by having the key file locally, it does not seem to be the root cause of the problem!

**Comment by ddelgrosso1** [comment] 2022-02-15 17:03
Just wanted to provide some updates and possible suggestions. Following the call chain down for generating a signed URL ultimately hits the [NodeJS Sign class](https://nodejs.org/api/crypto.html#class-sign). This is going to be an expensive operation in terms of CPU which would result in event loop delays. 

I'm trying to see what, if anything, can be done at the library level. More than likely this will need to be accounted for at the application level. Scaling up the number of application instances during times of expected high load might be one possibility. If you are using a platform that will allow you to adjust the number/size of CPUs and memory it might also be worth increasing these to see if better throughput is achieved.

**Comment by ddelgrosso1** [comment] 2022-02-25 19:47
As this is expected behavior given how signed URLs are generated I am going to close this issue. If there is additional information that would point to another cause, please feel free to reopen.

**Closed by ddelgrosso1** 2022-02-25 19:47 UTC
Labels: type: question, priority: p2, api: storage

**Comment by ddelgrosso1** [comment] 2022-02-28 20:36
Thanks for the update @oleurud!
