### ISSUE TITLE
NodeError: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by arnavzek** [googleapis/nodejs-storage#2379] opened 2023-11-30 21:54 UTC
#### Environment details

  - OS: Amazon Linux 2023/6.0.3
  - Node.js version: Node 18
  - `@google-cloud/storage` version: 7.7.0

#### Steps to reproduce

The library is working fine locally and one AWS EC@ but it produces the following error when deployed to AWS Beanstalk

```
web[12135]: NodeError: Cannot call write after a stream was destroyed
Nov 30 21:22:58 ip-172-31-39-94 web[12135]:    at doWrite (/var/app/current/node_modules/readable-stream/lib/_stream_writable.js:390:38)
Nov 30 21:22:58 ip-172-31-39-94 web[12135]:    at writeOrBuffer (/var/app/current/node_modules/readable-stream/lib/_stream_writable.js:381:5)
Nov 30 21:22:58 ip-172-31-39-94 web[12135]:    at Writable.write (/var/app/current/node_modules/readable-stream/lib/_stream_writable.js:302:11)
Nov 30 21:22:58 ip-172-31-39-94 web[12135]:    at HashStreamValidator.ondata (node:internal/streams/readable:777:22)
Nov 30 21:22:58 ip-172-31-39-94 web[12135]:    at HashStreamValidator.emit (node:events:517:28)
Nov 30 21:22:58 ip-172-31-39-94 web[12135]:    at addChunk (node:internal/streams/readable:335:12)
Nov 30 21:22:58 ip-172-31-39-94 web[12135]:    at readableAddChunk (node:internal/streams/readable:308:9)
Nov 30 21:22:58 ip-172-31-39-94 web[12135]:    at Readable.push (node:internal/streams/readable:245:10)
Nov 30 21:22:58 ip-172-31-39-94 web[12135]:    at HashStreamValidator._transform (/var/app/current/node_modules/@google-cloud/storage/build/src/hash-stream-validator.js:83:14)
Nov 30 21:22:58 ip-172-31-39-94 web[12135]:    at Transform._write (node:internal/streams/transform:175:8)

```

Code 

```
    const { buffer } = file;

    let name = nanoid();

    if (file.originalname) {
      name = name + path.extname(file.originalname).toLowerCase();
    }

    const blob = bucket.file(
      `${process.env.ENV_TYPE}/inwire/user-uploads/${name}`
    );
    const blobStream = blob.createWriteStream({
      resumable: false,
    });

    blobStream
      .on("finish", () => {
        // const publicUrl = util.format(
        //   `https://storage.googleapis.com/${bucket.name}/${blob.name}`
        // );
        resolve({ fileName: name });
      })
      .on("error", (data) => {
        console.log(data);
        reject(
          `Unable to upload image, something went wrong. Size:${
            file.size
          } File:${file.originalname} ${JSON.stringify(data)}`
        );
      })
      .end(buffer);

```

**Comment by arnavzek** [comment] 2023-12-03 18:39
It happens every single time. I don't think, I can help isolate this issue because I have switched to S3.

**Comment by MadeinFrance** [comment] 2023-12-04 14:45
@ddelgrosso1 same as @arnavzek provided with `resumable: false`, NodeJS  `v20`.

```js
import { Storage } from "@google-cloud/storage";

const storage = new Storage({
  projectId: 'id',
});
const bucket = storage.bucket('bucket_id');

const blob = bucket.file(name);
const stream = blob.createWriteStream({
  metadata: {
    contentType: 'webp',
  },
  resumable: false,
});
```

**Comment by ddelgrosso1** [comment] 2024-03-22 16:06
Apologies for the late reply, circled back on this today @MadeinFrance. I tried this in GCP Cloud Functions utilizing v7.8.0 of the library and was not able to reproduce the error. Are there any other steps of configuration you might be able to provide that would be helpful in recreating the issue?

**Comment by MadeinFrance** [comment] 2024-03-30 20:49
@ddelgrosso1 hi there, it's not reproducible on `v7.9.0`, I will stay on the latest version.

**Comment by ddelgrosso1** [comment] 2024-04-01 17:56
Going to close this out. If additional information becomes available please feel free to reopen / create a new issue.

**Closed by ddelgrosso1** 2024-04-01 17:56 UTC
Labels: type: bug, priority: p2, needs more info, api: storage
