### ISSUE TITLE
How to use Access key + Secret key to instantiate Storage instance

### ISSUE THREAD

**Issue by joshuarcher** [googleapis/nodejs-storage#2021] opened 2022-08-06 00:53 UTC
I'm working with a customer to move data from our system to their storage bucket and they've sent me the Service Account HMAC keys (access key + secret key).

**Here's what I have:**
- Project id
- Region
- Bucket
- Service account email
- Access Key
- Secret Key

Is there a way to use this without a service account json file?? I was hoping to do something like the below, but it doesn't work.

```
const storage = new Storage({
    projectId: "ENTER_PROJ_ID_HERE",
    credentials: {
        client_email: "ENTER_CLIENT_EMAIL_HERE",
        private_key: "ENTER_P_KEY_HERE",
    },
});
```

**Comment by ddelgrosso1** [comment] 2022-08-09 18:04
Hi @joshuarcher the `Storage` constructor has the ability to accept a custom auth client as the `authClient` argument. Some of the possibilities are documented [here](https://github.com/googleapis/google-auth-library-nodejs).

**Comment by danielbankhead** [comment] 2022-08-09 20:20
To add to @ddelgrosso1's suggestion, an `authClient` can be created like this: https://github.com/googleapis/google-auth-library-nodejs/blob/f483a6847fff7a0aa29176aa8704e61640146586/samples/credentials.js#L36-L42

And can be passed to `Storage` like so: https://github.com/googleapis/google-auth-library-nodejs/blob/f483a6847fff7a0aa29176aa8704e61640146586/samples/downscopedclient.js#L78-L83

Example:
```ts
import {GoogleAuth} from 'google-auth-library';
import {Storage} from '@google-cloud/storage';

const storage = new Storage({
  authClient: new GoogleAuth({
    credentials: {
      client_email: clientEmail,
      private_key: privateKey,
    },
  }),
});
```

However, your method should also work as `credentials` are passed to `GoogleAuth` from `Storage` here:

https://github.com/googleapis/nodejs-storage/blob/3ecb73134fff4f62fb2e30e54316138569ccf34a/src/nodejs-common/util.ts#L611-L622

What error are you receiving?

**Comment by ddelgrosso1** [comment] 2022-08-16 14:46
Going to close this issue since it is not clear what the error / problem encountered was. If more information becomes available or this is still a problem, feel free to reopen.

**Closed by ddelgrosso1** 2022-08-16 14:46 UTC
Labels: type: question, needs more info, api: storage, priority: p3

**Comment by bradisbell** [comment] 2023-03-30 03:28
This seems to be a duplicate of:  https://github.com/googleapis/nodejs-storage/issues/117

I'm running into the same problem.  It seems that the answer is, this library does not support HMAC authentication.  Is that correct?
