### ISSUE TITLE
Fallback to non-resumable not working when $HOME is not writable

### ISSUE THREAD

**Issue by ofrobots** [googleapis/nodejs-storage#181] opened 2018-04-26 17:28 UTC
The docs claim:

https://cloud.google.com/nodejs/docs/reference/storage/1.6.x/File#createWriteStream
> Resumable uploads require write access to the $HOME directory. Through config-store, some metadata is stored. By default, if the directory is not writable, we will fall back to a simple upload. However, if you explicitly request a resumable upload, and we cannot write to the config directory, we will return a ResumableUploadError.

However, I am getting the following error in an environment where `$HOME` is not writable.

```
A  Error: EROFS: read-only file system, mkdir '/home/.config' 
A      at Object.fs.mkdirSync (fs.js:885:18) 
A      at make (/srv/node_modules/make-dir/index.js:59:12) 
A      at make (/srv/node_modules/make-dir/index.js:66:5) 
A      at Function.module.exports.sync (/srv/node_modules/make-dir/index.js:82:9) 
A      at Configstore.get all [as all] (/srv/node_modules/configstore/index.js:34:13) 
A      at new Configstore (/srv/node_modules/configstore/index.js:25:47) 
A      at new Upload (/srv/node_modules/gcs-resumable-upload/index.js:64:22) 
A      at Upload (/srv/node_modules/gcs-resumable-upload/index.js:28:41) 
A      at File.startResumableUpload_ (/srv/node_modules/@google-cloud/storage/src/file.js:2278:22) 
A      at Pumpify.<anonymous> (/srv/node_modules/@google-cloud/storage/src/file.js:959:12) 
```

And the upload fails. The fallback to non-resumable uploads is not working as claimed in the docs.

**Comment by stephenplusplus** [comment] 2018-04-26 17:54
What version of GCS & code to reproduce?

**Comment by ofrobots** [comment] 2018-04-26 19:00
```
$ grep "google-cloud/storage" package-lock.json
    "@google-cloud/storage": {
      "resolved": "https://registry.npmjs.org/@google-cloud/storage/-/storage-1.6.0.tgz",
```

Code:
```ts
import * as express from 'express';
const Storage = require('@google-cloud/storage');

const config = {
  projectId: $INSERT_YOUR_PROJECT_ID,
  bucketName: $INSERT_YOUR_BUCKET_NAME
};
const storage = new Storage({projectId: config.projectId});

const BUCKET_URL = `https://storage.googleapis.com/${config.bucketName}`;

const app = express();

app.post('/upload', async (req, res) => {
  const id = 'a-random-uuid';
  const file = storage.bucket(config.bucketName).file(id);
  req.pipe(file.createWriteStream({gzip: true, public: true}))
      .on('error',
          (err: Error) => {
            res.status(500).send({err});
          })
      .on('finish', () => {
        const rawUrl = `${BUCKET_URL}/${id}`;
        res.status(200).send({rawUrl});
      });
});
app.listen(8080, (err: Error) => {
  if (err) {
    throw err;
  }
  console.log('Server listening on port 8080');
});
```

Hit it:
```
$ curl -X POST http://localhost:8080/upload -H 'Content-Type:application/json' -d @$HOME/$SOMEFILE
```

**Comment by ofrobots** [comment] 2018-04-26 22:58
The expected work-around of passing `resumable: false` option to `File#createWriteStream` doesn't seem to help.

This is a blocker for a product launch, and no work-around is known at this point. Can the priority be increased?

**Comment by stephenplusplus** [comment] 2018-04-27 14:38
Looks like we haven't released the behavior you're expecting: https://github.com/googleapis/nodejs-storage/pull/165

@frankyn @jonparrott @alexander-fenster -- advice on how to proceed, please! Would you like a new release without KMS so that this product launch is unblocked, or wait for KMS?

**Comment by jonparrott** [comment] 2018-04-27 16:25
Let's wait for KMS unless this is a P0 bug.

**Comment by frankyn** [comment] 2018-04-27 17:46
Wait on merging KMS, I don't have opinions on cutting release for this bug.

**Comment by ofrobots** [comment] 2018-04-27 18:52
Is cutting a release expensive?

**Comment by ofrobots** [comment] 2018-04-28 00:00
I am personally blocked on this bug as well. What's the ETA on KMS getting into a release?

**Comment by jonparrott** [comment] 2018-05-01 17:42
@stephenplusplus since we haven't merged KMS stuff, can we go ahead and cut a release?

**Comment by ofrobots** [comment] 2018-05-04 01:44
*gentle ping*

**Comment by stephenplusplus** [comment] 2018-05-07 13:36
Blocked on https://github.com/googleapis/nodejs-storage/pull/190

**Comment by stephenplusplus** [comment] 2018-05-22 17:04
1.7.0 released with this feature :)

**Closed by stephenplusplus** 2018-05-22 17:04 UTC
Labels: priority: p2, type: bug
