### ISSUE TITLE
Allow users to configure Cache-Control headers through the `cacheControl` or `metadata.cacheControl` options in  `File.save`

### ISSUE THREAD

**Issue by amiller-gh** [googleapis/nodejs-storage#1979] opened 2022-06-06 03:05 UTC
**Is your feature request related to a problem? Please describe.**
It does not appear to currently be possible 

`File.save()` calls out to `File.createWriteStream()`
https://github.com/googleapis/nodejs-storage/blob/1d7d075b82fd24ea3c214bd304cefe4ba5d8be5c/src/file.ts#L1805

Which, calls out to `startResumableUpload_` or `startSimpleUpload_` depending on the `resumable: false` option.

https://github.com/googleapis/nodejs-storage/blob/main/src/file.ts#L3717

Both of these methods summarily ignore `cacheControl` passed in the options has, or `cache-control` (including camel cased) passed in the `metadata` option property, despite being supported by other file manipulation methods: https://github.com/googleapis/nodejs-storage/issues/1422

Incidentally, it seems to also ignore all other valid metadata options including contentDisposition, contentLanguage, customTime, and other custom, user-provided metadata properties.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/7856443/172087530-bfb39bfb-0a1d-4e68-89d6-cd5f967137d8.png">

 **Describe the solution you'd like**
For `File.save()` to respect custom metadata properties.

 **Describe alternatives you've considered**
Use another library that supports it by hitting up the REST API directly... not preferable since this is the officially supported Node.js library!

 **Additional context**
N/A

**Comment by shaffeeullah** [comment] 2022-06-07 15:10
Hi @amiller-gh , 

I'm unable to reproduce this issue. I am able to set `cacheControl` by calling
```
await file.save("hello", {metadata: {cacheControl: CACHE_CONTROL}});
```
All metadata fields should be available on this method via the `metadata` field in `options`

Can you provide the code snippet that you're trying?

**Comment by amiller-gh** [comment] 2022-06-10 16:14
Interesting – failed for me. I'll try again in the next day or so.

**Comment by shaffeeullah** [comment] 2022-08-01 17:11
@amiller-gh Closing this due for now. Please reopen if you're still seeing this issue.

**Closed by shaffeeullah** 2022-08-01 17:11 UTC
Labels: type: feature request, needs more info, api: storage, priority: p3
