### ISSUE TITLE
Invalid links rendered from TSDoc

### ISSUE THREAD

**Issue by kmishmael** [googleapis/nodejs-storage#2219] opened 2023-06-11 12:28 UTC
Hi
While going through the TSDoc Documentation in VSCode, I noticed that clicking on a link redirects me to a 404 page. Upon further investigation, I discovered that the way the links were written posed difficulties for VSCode to render them correctly, and it also did not adhere to the recommended format of TSDoc.

For instance, the following link:
```ts
/**
* See {@link https://cloud.google.com/storage/docs/json_api/v1/objects/list| Objects: list API Documentation}
*/ 
```
is rendered as:
```
https://cloud.google.com/storage/docs/json_api/v1/objects/listObjects:
```
instead of the desired:
```
https://cloud.google.com/storage/docs/json_api/v1/objects/list
```
To address this issue, it is recommended to follow the TSDoc format, which involves placing whitespace before and after the `|` symbol:
```ts
/**
* See {@link https://cloud.google.com/storage/docs/json_api/v1/objects/list | Objects: list API Documentation}
*/ 
```
By making this adjustment, the links will be rendered correctly within VSCode and conform to the recommended TSDoc format.

**Comment by ddelgrosso1** [comment] 2023-06-12 13:37
Hi @kmishmael thank you for opening an issue. We are currently planning to rework docs in TSDoc format. Please see issue #2111. Since this is a duplicate of that issue, I am going to close it. Please feel free to add any additional feedback to that issue.

**Closed by ddelgrosso1** 2023-06-12 13:37 UTC
Labels: type: bug, priority: p2, api: storage
