### ISSUE TITLE
Failing to upload big files to bucket - Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by dawidreedsy** [googleapis/nodejs-storage#2167] opened 2023-03-22 11:39 UTC
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS: alpine 3.16 
  - Node.js version: 18.10.0
  - npm version: 18.10.0
  - `@google-cloud/storage` version: 6.9.4

#### Steps to reproduce

  1. Upload file of size 1GB
  2. Getting error `Cannot create a string longer than 0x1fffffe8 characters`

The same issue as described on [stackoverflow](https://stackoverflow.com/questions/69636432/how-to-chunk-and-upload-a-large-file-to-google-bucket) I think this is `googleapis/nodejs-storage` responsibility to chunk the file and upload it accordingly not an external user.

**Comment by ddelgrosso1** [comment] 2023-03-22 15:01
Hi @dawidreedsy can you please share a snippet showing how you are attempting to upload the file and a full stack trace if you have it. We have not had any recent issues regarding file sizes and I routinely test with files > 1GB.

**Comment by dawidreedsy** [comment] 2023-03-22 15:15
Worth to mention that after we get this error logged, our instance is blowing up from Out Of Memory error, I think you may need to try in memory restricted environment.

**Comment by ddelgrosso1** [comment] 2023-03-22 15:24
Can you share a bit about the environment specs that your code is running in? I suspect you are right, this likely is due to resource constraints / environment specific.

I just ran this test in my local environment:

```javascript
import {Storage} from '@google-cloud/storage';

const s = new Storage({projectId: 'my-project'});
const b = s.bucket('my-bucket');

try {
    await b.upload('2-GB-File.dat', {destination: 'large-file.dat', resumable: false, validation: 'crc32c'});
  } catch(e) {
    console.error(e);
}
```

**Comment by siva54** [comment] 2023-03-22 16:47
Hi @ddelgrosso1 . Were you able to handle this issue or come up with a solution? I have the same issue within my project too.

**Comment by ddelgrosso1** [comment] 2023-03-22 17:22
@siva54 / @dawidreedsy can either of you do a `npm ls node-fetch` and tell me what version you see?

**Comment by dawidreedsy** [comment] 2023-03-22 19:01
@ddelgrosso1 
```
**** OUR LIB *****
├─┬ @google-cloud/storage@6.9.4
│ ├─┬ gaxios@5.0.2
│ │ └── node-fetch@2.6.7
│ └─┬ teeny-request@8.0.2
│   └── node-fetch@2.6.7 deduped
└─┬ *** OUR OTHER INTERNAL LIB ***
  └─┬ @google-cloud/pubsub@3.2.1
    └─┬ google-gax@3.5.2
      └── node-fetch@2.6.7 deduped
```

**Comment by dawidreedsy** [comment] 2023-03-22 19:08
> Is there any other processing of the file you are doing?

Yes we doing quite a bit processing on the instance, as this is a worker that handles larger tasks, however each instance is processing only one task at time, so there shouldn't be any concurrency issue.

**Comment by dawidreedsy** [comment] 2023-03-22 19:25
I saw that you have option `chunkSize` tomorrow morning will try that and see if it helps.

**Comment by ddelgrosso1** [comment] 2023-03-22 19:40
From the trace you provided above it is leading me to this line: https://github.com/node-fetch/node-fetch/blob/1ef4b560a17e644a02a3bfdea7631ffeee578b35/src/body.js#L132. However, when I step through this in a debugger the times that this is hit for a response the size of the buffer is no where near 512MB/1GB. What type of files are these? Are you setting any kind of header information?

**Comment by dawidreedsy** [comment] 2023-03-22 19:47
> From the trace you provided above it is leading me to this line: https://github.com/node-fetch/node-fetch/blob/1ef4b560a17e644a02a3bfdea7631ffeee578b35/src/body.js#L132. However, when I step through this in a debugger the times that this is hit for a response the size of the buffer is no where near 512MB/1GB. What type of files are these? Are you setting any kind of header information?

They are zip files, no any specific header information.

**Comment by dawidreedsy** [comment] 2023-03-22 19:50
> From the trace you provided above it is leading me to this line: https://github.com/node-fetch/node-fetch/blob/1ef4b560a17e644a02a3bfdea7631ffeee578b35/src/body.js#L132. 

yeah the response would need to contain the whole zip file..., maybe some weird error just tries to dump the content of the file to error response?

**Comment by dawidreedsy** [comment] 2023-03-23 12:09
@ddelgrosso1 
FYI we added the option `chunkSize = 100 * 2**20 //100Mb` and it works without any issue

**Comment by dawidreedsy** [comment] 2023-03-23 15:00
@ddelgrosso1 

I actually was a bit wrong in my last example of when this happens as we also had `makePublic` call.
```
    const options = {
      destination: destination,
      resumable: false,
      validation: 'crc32c',
    };

try {
  const [file] = await this.bucket.upload(filePath, options);
  await file.makePublic()
} catch(err) {
  logger.error('Fails here')
}
    
```

I actually removed `makePublic` call and added `chunkSize`, so it might be make public call that causing it.  The options looks like this now:
```
    const options = {
      destination: destination,
      resumable: false,
      validation: 'crc32c',
      chunkSize = 100 * 2**20,
      public: true,
    };
```

I doubt it could come from makePublic request, but yeah this is the 2 things i changed, and no more errors

**Comment by ddelgrosso1** [comment] 2023-03-28 13:53
@dawidreedsy is there anyway you could log the raw response from the call to `upload`? I'm at a loss for why you are seeing such a large response which should not be the case.

**Comment by dawidreedsy** [comment] 2023-03-28 14:01
@ddelgrosso1 
Will try to find some time to get it for you, but cannot promise.

**Comment by dawidreedsy** [comment] 2023-04-25 06:30
@ddelgrosso1 
No it is not happening after I used the chunk option.
Sorry, couldn't reproduce it on any testing environment. I guess it needs to be under pressure to throw this error and I cannot put the error back to production to catch the body.

**Comment by ddelgrosso1** [comment] 2023-05-01 14:50
Going to close this for now as we are unable to reproduce it. If any additional information becomes available that might help us reproduce / debug, please feel free to reopen.

**Closed by ddelgrosso1** 2023-05-01 14:50 UTC
Labels: type: bug, needs more info, api: storage, priority: p3
