### ISSUE TITLE
Getting 408 on High Load save

### ISSUE THREAD

**Issue by daneshka** [googleapis/nodejs-storage#833] opened 2019-08-27 21:14 UTC
#### Environment details

  - OS: alpine
  - Node.js version: 10.16
  - npm version: 6.9.0
  - `@google-cloud/storage` version:

#### Steps to reproduce

The error only happens on high load save on the same Bucket.
We use GUID in the URI.
It sends HTML in the error message!

```json
{
  "message":"Cannot parse response as JSON: <!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 408 (Request Timeout)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>408.</b> <ins>That’s an error.</ins>\n  <p>Your client has taken too long to issue its request.  <ins>That’s all we know.</ins>\n",
  "exception":{
    "exceptionMessage":"Cannot parse response as JSON: <!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 408 (Request Timeout)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>408.</b> <ins>That’s an error.</ins>\n  <p>Your client has taken too long to issue its request.  <ins>That’s all we know.</ins>\n",
    "stacktrace":"InternalError: Cannot parse response as JSON: <!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 408 (Request Timeout)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>408.</b> <ins>That’s an error.</ins>\n  <p>Your client has taken too long to issue its request.  <ins>That’s all we know.</ins>\n\n    at GcsClient.filterError (/opt/bss/dist/src/services/gcs-client.js:63:16)\n    at getFile.save.catch.error (/opt/bss/dist/src/services/gcs-client.js:40:42)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
  },
  "code":13,
  "name":"InternalError",
  "level":"ERROR",
  "loggerName":"bss:middleware:error",
  "traceId":"0",
  "spanId":"0",
  "requestId":"7f975f2e-3516-9d0a-bafe-eb91672d355a",
  "date":"2019-08-27T21:06:21.013Z"
}
```

The main message in the HTML is:
```
408. That’s an error. Your client has taken too long to issue its request. That’s all we know.
```

Thanks!

**Comment by laljikanjareeya** [comment] 2019-08-28 12:10
A few questions to help us work out what's happening:
- what is the size of your data/file that you are uploading?
- Does this happen all the time or just occasionally?
- Please Provide code sample that you are using.

**Comment by crwilcox** [comment] 2019-08-29 20:16
@daneshka, have you tried retrying on error? If you retry after the 408 is it successful?

**Comment by daneshka** [comment] 2019-08-29 22:02
@crwilcox 
No, We only use the built-in retry feature.
I can implement a retry and get back to you.

**Comment by crwilcox** [comment] 2019-08-29 22:45
@daneshka it would be interesting to understand if this is a transient error. I imagine it is and we can likely harden the client around this.

**Comment by daneshka** [comment] 2019-09-10 00:17
We didn't see the issue after adding our own retry on top of the library.

**Comment by stephenplusplus** [comment] 2019-10-03 14:12
@crwilcox how do you think we should proceed here? Is there anything we can do?

**Comment by stephenplusplus** [comment] 2019-11-22 20:57
Our uploads all use our streaming API underneath the surface, so `file.save(blob)` is akin to `file.createWriteStream({resumable:false}).end(blob)`. The streaming APIs are not able to resend data after a response from the server-- it can only do that if there was an issue preflight. Once data goes out from a stream, we can't rewind it arbitrarily to get it back.

However, I don't think there's a reason `file.save()` *needs* to use the streaming API underneath. We can just send the request like any other, putting the blob in the request body. Then, it would benefit from our normal exponential retry logic.

Although, 408 error codes are not currently being retried. We have a [small whitelist of retried error codes](https://github.com/googleapis/nodejs-common/blob/93212e075b0c90d1aa69f62c8dab3608a2d9d868/src/util.ts#L517): 429, 500, 502, and 503.

The benefits of making the change to `file.save()` may be unsubstantial, however, as this would only improve the `file.save()` story without having any effect on `file.createWriteStream()` users.

**Comment by klon** [comment] 2020-03-09 10:58
We also get 408 also when using file.createWriteStream() to stream data to a file, it happens at around 7 minutes consistently. We basically can't stream data that takes more than 7 minutes to upload. It is a complete show stopper for us.

Using Node v12.16.1 and @google-cloud/storage 4.3.1

**Comment by surjikal** [comment] 2020-03-10 00:13
Just got this error today when streaming through image data.

**Comment by simllll** [comment] 2020-04-01 11:54
Ran into the same issue today. 
we use
```ts
 const fileStream = myFile.createWriteStream({
			// Support for HTTP requests made with `Accept-Encoding: gzip`
			metadata: {
				contentType: 'application/json'
				// contentEncoding: 'gzip'
			},
			gzip: true,
			resumable: false,
			validation: 'md5'
			// validation: false
		});
```
to create the stream, and also catch all errors of the stream, but we get an uncatchable error when the response is 408:
```
Error: Cannot parse response as JSON: <!DOCTYPE html> // truncated..whole html body is here
  at Util.parseHttpRespBody (/var/app/current/node_modules/@google-cloud/common/build/src/util.js:188:42)
    at Util.handleResp (/var/app/current/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at /var/app/current/node_modules/@google-cloud/common/build/src/util.js:432:22
    at onResponse (/var/app/current/node_modules/retry-request/index.js:206:7)
    at /var/app/current/node_modules/teeny-request/build/src/index.js:170:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) { killProcess: true, job: 'backend/job.js,backend/syncData.js' }

```

**Comment by simllll** [comment] 2020-04-01 12:15
Regarding my uncatchable error, could it be that createWriteStream does not forward errors correclty? createWriteStream is using dupleify behind the scene, but there is no on('error') method registered on the "fileWriteStream". Not sure, just an idea I though I write down.

**Comment by stephenplusplus** [comment] 2020-04-01 14:15
@simllll is there any chance you could provide a runnable example and any more details about what is happening when the error occurs?

**Comment by simllll** [comment] 2020-04-01 17:17
That's the struggle with this issue, it only happens on production, and I believe it is related either to high load (like the OP) or due to too many parallel transactions. I couldn't find a way to reproduce the original timeout issue, but this one is gone since adding the 408 to retryable errors.
To reproduce just the non catchable error, I was able to reproduce this by adding 

throw new Error('TEST');
in the     handleResp(err, resp, body, callback) function of @google-cloud/common/build/src/util.ts

I was not able to catch this error so far, probably because it's not a stream error itself, it's a thrown error (like the one where JSON cannot be parsed I guess)

**Comment by simllll** [comment] 2020-04-01 17:21
Indeed, if I wrap the handleResp in a try / catch block and catch the error:
```ts
try {
... 
} catch (err) {
					callback(err);
				}
```

I'm able to catch the error :)

**Comment by alarmatwork** [comment] 2020-04-17 07:05
Getting this "Error 408" quite a lot lately. It's making storage very unreliable, it messes up out process a lot, even out load is minimal. Pretty much one file is uploaded and filesize is ~ 400KB

**Comment by pebo** [comment] 2020-04-25 08:50
Same issue here. We're seeing an increase in 408 errors lately. It would be great if the retry PR https://github.com/googleapis/nodejs-common/pull/562 could be merged.

**Comment by stephenplusplus** [comment] 2020-05-08 14:54
@pebo that PR wasn't moving too quickly, so I've thrown together a new one: https://github.com/googleapis/nodejs-common/pull/578. Hopefully, we can merge and release soon.

**Comment by pebo** [comment] 2020-05-12 20:45
@stephenplusplus thanks for the PR, but after checking our latest error latest logs this PR (which adds retries for 408) might make GCS behave even worse for us.

We're occasionally seeing very long upload times (>6minutes!) for tiny 90byte files before GCS throws the exception mentioned in this issue. 

The code is running in Cloud Run on the node:12-slim base image and the container had successfully written to GCS a few seconds before the request that caused 408 and successfully handles writes triggered by other invokations just after the failing operation.

The code path that fails with 408:

```
    const options = {
      resumable: false,
      contentType: 'application/json'
    };
    await file.save(JSON.stringify(someObject), options);
```

Can we reduce the timeouts for writes to GCS (then retries makes sense)?

**Comment by stephenplusplus** [comment] 2020-06-15 19:28
We now retry 408 errors and allow `options.timeout` if that helps working around this issue. I'm going to close, but please let me know if there's more we can do.

**Closed by stephenplusplus** 2020-06-15 19:28 UTC
Labels: api: storage, external, priority: p2, type: bug

**Comment by evil-shrike** [comment] 2024-08-13 21:46
I'm on "@google-cloud/storage": "^7.1.0",
but it's still happening for me on high load (many parallel Cloud Run instances writing files on the same bucket)
WriteStreams are created as:
```
      writeStream = file.createWriteStream({
        // surprisingly setting highWaterMark is crucial,
        // w/ o it we'll get unlimited memory growth
        highWaterMark: 1024 * 1024,
        timeout: 0,
        resumable: true,
        validation: false,
      });
```
In logs I see some html error. Why are they HTML?! Isn't it a bug by itself (returning errors in HTML on API requests)?
```
Error: Retry limit exceeded - <!DOCTYPE html>
<html lang=en>
<meta charset=utf-8>
<meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
<title>Error 408 (Request Timeout)!!1</title>
<style>
*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
</style>
<a href=//www.google.com/><span id=logo aria-label=Google></span></a>
<p><b>408.</b> <ins>That’s an error.</ins>
<p>Your client has taken too long to issue its request. <ins>That’s all we know.</ins>
at Upload.attemptDelayedRetry (/workspace/node_modules/@google-cloud/storage/build/src/resumable-upload.js:705:26)
at Upload.onResponse (/workspace/node_modules/@google-cloud/storage/build/src/resumable-upload.js:669:18)
at Upload.makeRequestStream (/workspace/node_modules/@google-cloud/storage/build/src/resumable-upload.js:655:40)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Upload.startUploading (/workspace/node_modules/@google-cloud/storage/build/src/resumable-upload.js:496:26)
```
