### ISSUE TITLE
Get file reference from URI

### ISSUE THREAD

**Issue by paymog** [googleapis/nodejs-storage#2057] opened 2022-09-03 18:29 UTC
Does this library offer users a way to get a reference to a file in GCS from a URI? Suppose I have a uri like the following: `gs://mybucket/myvideo.mov`. 

Ideally I'd like to have an api like the following:

```
import { Storage } from '@google-cloud/storage';
const storage = new Storage();

const file = storage.getFileFromUri("gs://mybucket/myvideo.mov")

// do stuff with the file like like change it's metadata or download it
```

Is this possible or will I have to write my own utility function to parse the `gs://...` uri?

**Comment by danielbankhead** [comment] 2022-09-06 20:26
Hey @paymog, this sounds a lot like:
- https://github.com/googleapis/nodejs-storage/issues/1898

We think this would be a handy feature! We'll add this functionality in a future release.

**Comment by shaffeeullah** [comment] 2022-09-08 20:23
closing this as a duplicate of https://github.com/googleapis/nodejs-storage/issues/1898
we'll track updates to this feature request there.

**Closed by shaffeeullah** 2022-09-08 20:23 UTC
Labels: type: feature request, api: storage, priority: p3
